### ISSUE TITLE
Cannot sign back in after signing out

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#1]
I was logged in, selected "Logout" from the app bar and it logged me out. Fine.

However, I was not able to log back in after entering my account credentials. Pressing "enter" on the keyboard did not work, as well as the Sign in button was not visible at all.

**Comment by Top-Cat** [comment]
Can not reproduce from the above steps. When logging out I see the button.

Adding enter to submit the form would probably help.

The workaround is to force quit the app or restart your phone and log in.

**Comment by Top-Cat** [comment]
Closing due to lack of response
