### ISSUE TITLE
Notify about new trade offers via Notification Center

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#12]

**Comment by Top-Cat** [comment]
This will basically need a thread to poll FetchConfirmations unless you can find a way to get Google Cloud Messaging to work on WP.

I'd also like to get rid of the silly regexes in FetchConfirmations if we go that route.

**Comment by GAMELASTER** [comment]
Hmm, its isnt possible to use a WP pull request service? And for now I think its enough to run a bg service what will push notification.

**Comment by Top-Cat** [comment]
Steam don't run one so no?

**Comment by GAMELASTER** [comment]
Yea, so then only background service, or?

**Comment by fourzerofour** [comment]
If you can set up bg service, you can poll request (require session and steamguard cookies) to this link `https://steamcommunity.com/actions/GetNotificationCounts`. That's where steam client poll notification info to be shown in the client. Last I checked, the notification counts returned in the json reply is in the order of comments, items, invites, gifts, offlinemessages, tradeoffers, gameturns, and moderatormessages

**Comment by Top-Cat** [comment]
You don't need any of those numbers, confirmations aren't listed in the steam client.

**Comment by setoy** [comment]
The android client does this kind of polling, could try to get the url to which it's polling or pushing.

**Comment by fourzerofour** [comment]
Sorry if I wasn't clear. My reply above was in response to the topic title 'notify about new trade'. But yeah if you're interested in trade confirmations then you're right the notification wont give you the number

**Comment by Top-Cat** [comment]
The android client doesn't poll, it uses GCM.

**Comment by Top-Cat** [comment]
Investigation reveals this might be as much as 30 minutes late as background tasks are really bad.

**Comment by fourzerofour** [comment]
Better late than never, no?

**Comment by Top-Cat** [comment]
Yeah, I'm still going to try and add this soon

**Comment by Top-Cat** [comment]
Added in #48

**Comment by fourzerofour** [comment]
Sorry what was actually added in #48? Notification for **trade confirmation** or **trade offers** as mentioned on issue subject? Because I received (unread) pending trade offers in steam client since yesterday but I haven't gotten any notification about that from the authenticator on my mobile.

**Comment by Top-Cat** [comment]
Notification for trade confirmations were added, you can't actually do anything with trade offers in the app.
