### ISSUE TITLE
Better handling when internet connection is inaccessible

### ISSUE THREAD

**Issue by fourzerofour** [Top-Cat/UnofficialSteamAuthenticator#17]
So I experience few crashes that are always reproducible when I use the authenticator (with my accounts already set up) while not being connected to internet or having flaky connection. For example, when I go into Switch account screen, I always get instant crash there. I guess it needs internet to fetch the display name of every accounts listed in the screen. I suppose you could keep the last display names that were successfully retrieved and fallback to them if you cannot fetch the current display names of those accounts from steam api

**Comment by setoy** [comment]
Which version are you using? Hamburger menu -> About.

v1.2.0 introduced caching, maybe that's a remedy to that issue?

**Comment by fourzerofour** [comment]
It looks here I'm already using 1.2
