### ISSUE TITLE
Export / Import to SDA

### ISSUE THREAD

**Issue by Top-Cat** [Top-Cat/UnofficialSteamAuthenticator#18]
Allow people to import maFiles and create them too.

Not sure how people would react to this security-wise, potential to duplicate authenticator with access to someone's phone.

**Comment by fourzerofour** [comment]
On a related note, does the app currently support automatic app setting backup to cloud? Also will the app data be restored automatically when I reinstall the app?

**Comment by Top-Cat** [comment]
Nothing is saved to the cloud, this is mostly for user security. Everyone's first question about this app is "will it steal my data?" and I like being able to say their data doesn't leave the device.

**Comment by setoy** [comment]
A setting (#11) would be nice... I deem the Microsoft Cloud to be secure, so more convenience would be nice... Would also be more error-prone when bricking or re-flashing the device... What about buying a new device? Would be a new device ID then, unless I restore the app?

**Comment by fourzerofour** [comment]
Fair enough but if that case, there must be a way to manually export and restore the app data for case like when users need to reinstall the app eg in case of switching/installing to new device

**Comment by Top-Cat** [comment]
@setoy I believe it syncs all of your devices.
I'm more worried a sync will go wonky and you'll lose an account.

The bigger issue is having to migrate existing data with the above constraint.

**Comment by setoy** [comment]
@Top-Cat Yeah, it syncs all devices - but a new device should yield a new device id, shouldn't it? But it wouldn't, because it's synced with the old device id... Or am I missing something?

**Comment by Top-Cat** [comment]
No, the generated device id is stored with your steam guard properties.

I've heard differing accounts of how important the device id even is. In my experience changing it at all leads to confirmations only showing up in one place or not at all. But other people have said that randomly changing it is sometimes the only way to get new confirmations out of it.

I don't think that's really the issue here anyway.

**Comment by Top-Cat** [comment]
On the actual topic of this issue there are some options on ways to accomplish this, SDA imports from android using adb to export if needed and copy a file from the phone automatically. We could maintain an encrypted file on the sd card, but it would be nice to not have to do that.
Any further suggestions welcome.

Phone -> SDA
- Export a .maFiles file on the phone's sd card for the user to copy and manually import into SDA (Easy but clunky for users)
- Maintain a .maFiles folder on the phone's sd card and find it with MTP (Easy for users if it works, maintaining state in two places isn't ideal)
- Use zeroconf to find computers running sda and implement a running service (Hard and probably still clunky)

SDA -> Phone
- QR Code magic (Easy all round, but only works one way)
- Import file from phone's sd card (Easy if we only allow one location, but clunky for users)
- Zeroconf (Hard and clunky)

**Comment by Top-Cat** [comment]
Simple export implemented in #34

**Comment by Top-Cat** [comment]
Completed in #68

**Comment by GAMELASTER** [comment]
Sorry for writing to closed issue, but I can't found the option to import maFile. I found only export. How to import it?

**Comment by hypixus** [comment]
@GAMELASTER These changes should be added to Windows Store as soon as tests will be completed.
