### ISSUE TITLE
Languages support improvment + POLISH TRANSLATION

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#19]
Hello

At first, I would like to show my translation of this useful app to my language - Polish.
Many of Polish users felt lack of application like this one - me too, until I found it on
Market :D Now, I've made translation of original Resources.resw file to my language.
Please check it for any bugs before introducing it to offical release. Also, please
consider looking at button labels maximum size - my translation made those usually
longer than expected, mostly by using "mobilny token urzytelniający" instead of
"authenticator".

At second, please add some sort of "example" resources file, which could make
translating much easier for people without any knowledge of making XML resource
files.

In case whole file wouldn't show up with this post, I paste it here (buggy web browser
on Raspberry Pi):

﻿<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="Authenticator_Unlink_Failed_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Unlink_Failed_Message" xml:space="preserve">
    <value>Błąd przy odłączaniu!</value>
  </data>
  <data name="UiCommand_Ok_Text" xml:space="preserve">
    <value>OK</value>
  </data>
  <data name="UiCommand_Cancel_Text" xml:space="preserve">
    <value>Anuluj</value>
  </data>
  <data name="Authenticator_Unlink_Prompt_Message" xml:space="preserve">
    <value>Czy jesteś pewien? To spowoduje blokadę wymian na minimum 7 dni.</value>
  </data>
  <data name="Authenticator_Unlink_Prompt_Title" xml:space="preserve">
    <value>Odłączyć?</value>
  </data>
  <data name="AccountsHeadline.Text" xml:space="preserve">
    <value>Konta</value>
  </data>
  <data name="LoginHeadline.Text" xml:space="preserve">
    <value>Zaloguj</value>
  </data>
  <data name="LoginBtn.Content" xml:space="preserve">
    <value>Zaloguj</value>
  </data>
  <data name="TxtAddAuthenticator.Text" xml:space="preserve">
    <value>Dodaj mobilny token urzytelniający</value>
  </data>
  <data name="TxtPhoneNumber.Text" xml:space="preserve">
    <value>Wpisz numer telefonu w następujący sposób: +{cC} Numer-telefonu (tj. +48 123-456-789).</value>
  </data>
  <data name="TxtUsername.Text" xml:space="preserve">
    <value>Nazwa użytkownika</value>
  </data>
  <data name="TxtPassword.Text" xml:space="preserve">
    <value>Hasło</value>
  </data>
  <data name="User_Logout_Prompt_Message" xml:space="preserve">
    <value>Czy jesteś pewien? To spowoduje usunięcie tego konta także z listy użytkowników.</value>
  </data>
  <data name="User_Logout_Prompt_Title" xml:space="preserve">
    <value>Wylogować?</value>
  </data>
  <data name="UiCommand_Yes_Text" xml:space="preserve">
    <value>Tak</value>
  </data>
  <data name="UiCommand_No_Text" xml:space="preserve">
    <value>Nie</value>
  </data>
  <data name="TxtEnterEmailCode.Text" xml:space="preserve">
    <value>Wpisz kod z e-maila</value>
  </data>
  <data name="TxtEnterTheCaptcha.Text" xml:space="preserve">
    <value>Wpisz znaki poniżej</value>
  </data>
  <data name="TxtEnterTwoFactor.Text" xml:space="preserve">
    <value>Wpisz kod z mobilnego tokena urzytelniającego</value>
  </data>
  <data name="LoginResult_GeneralFailure_Text" xml:space="preserve">
    <value>Nieznany błąd.</value>
  </data>
  <data name="LoginResult_BadRSA_Text" xml:space="preserve">
    <value>Nieznany błąd.</value>
  </data>
  <data name="LoginResult_BadCredentials_Text" xml:space="preserve">
    <value>Nieprawidłowe dane logowania.</value>
  </data>
  <data name="LoginResult_TooManyFailedLogins_Text" xml:space="preserve">
    <value>Za dużo błędów.</value>
  </data>
  <data name="Need2Fa" xml:space="preserve">
    <value>Potrzebny mobilny token urzytelniający.</value>
  </data>
  <data name="AreYouHuman" xml:space="preserve">
    <value>Czy jesteś człowiekiem?</value>
  </data>
  <data name="TxtLinkAuthenticatorHeadline.Text" xml:space="preserve">
    <value>Połącz mobilny token urzytelniający</value>
  </data>
  <data name="BtnLink.Content" xml:space="preserve">
    <value>Połącz</value>
  </data>
  <data name="TxtLinkAuthenticatorSummary.Text" xml:space="preserve">
    <value>Musisz ustawić to urządzenie jako mobilny token zanim będziesz uzyskiwać kody lub potwierdzenia wymian na Steam.</value>
  </data>
  <data name="SteamGuardButton.Label" xml:space="preserve">
    <value>Kody</value>
  </data>
  <data name="ConfirmationsButton.Label" xml:space="preserve">
    <value>Potwierdzenia</value>
  </data>
  <data name="MessageButton.Label" xml:space="preserve">
    <value>Chat</value>
  </data>
  <data name="UsersButton.Label" xml:space="preserve">
    <value>Zmień konto</value>
  </data>
  <data name="LogoutButton.Label" xml:space="preserve">
    <value>Wyloguj</value>
  </data>
  <data name="AboutButton.Label" xml:space="preserve">
    <value>O aplikacji</value>
  </data>
  <data name="BtnUnlink.Content" xml:space="preserve">
    <value>Odłącz</value>
  </data>
  <data name="BtnContinue.Content" xml:space="preserve">
    <value>Kontynuuj</value>
  </data>
  <data name="TxtSmsCode.Text" xml:space="preserve">
    <value>Wpisz kod z SMS-a</value>
  </data>
  <data name="Authenticator_Link_UnknownError_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Link_UnknownError_Message" xml:space="preserve">
    <value>Wystąpił nieznany błąd podczas łączenia mobilnego tokena.</value>
  </data>
  <data name="Authenticator_Link_AlreadyLinked_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Link_AlreadyLinked_Message" xml:space="preserve">
    <value>Już masz inne urządzenie ustawione jako mobilny token. Odłącz go od konta i spróbuj ponownie.</value>
  </data>
  <data name="EnterPhoneNumber" xml:space="preserve">
    <value>Wpisz numer telefonu</value>
  </data>
  <data name="BadCode" xml:space="preserve">
    <value>Zły kod</value>
  </data>
  <data name="TxtRevocationExp1.Text" xml:space="preserve">
    <value>Mobilny token nie został jeszcze połączony.

Przed zakończeniem, zapisz kod ratunkowy - pozwoli to odzyskać konto.</value>
  </data>
  <data name="TxtRevocationExp2.Text" xml:space="preserve">
    <value>Będziesz potrzebował tego kodu, jeśli stracisz swój telefon. NIE BĘDZIESZ MIAŁ MOŻLIWOŚCI ZOBACZYĆ GO PONOWNIE! Zapisz go więc, teraz.

Nikomu go nie podawaj.</value>
  </data>
  <data name="GeneratingCode_Ellipsis" xml:space="preserve">
    <value>Generowanie kodu...</value>
  </data>
  <data name="MainPage_AccountText_Format" xml:space="preserve">
    <value>{0} ({1})</value>
  </data>
  <data name="About_Headline.Text" xml:space="preserve">
    <value>Informacje o aplikacji</value>
  </data>
  <data name="About_AppVersion.Text" xml:space="preserve">
    <value>Wersja</value>
  </data>
  <data name="About_AppCreator.Text" xml:space="preserve">
    <value>Twórca</value>
  </data>
  <data name="About_AppSource.Text" xml:space="preserve">
    <value>Kod źródłowy</value>
  </data>
  <data name="NewUserButton.Label" xml:space="preserve">
    <value>Dodaj</value>
  </data>
  <data name="SwitchUserButton.Label" xml:space="preserve">
    <value>Zmień konto</value>
  </data>
</root>

**Comment by hypixus** [comment]
﻿<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" />
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string" />
              <xsd:attribute name="name" type="xsd:string" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="Authenticator_Unlink_Failed_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Unlink_Failed_Message" xml:space="preserve">
    <value>Błąd przy odłączaniu!</value>
  </data>
  <data name="UiCommand_Ok_Text" xml:space="preserve">
    <value>OK</value>
  </data>
  <data name="UiCommand_Cancel_Text" xml:space="preserve">
    <value>Anuluj</value>
  </data>
  <data name="Authenticator_Unlink_Prompt_Message" xml:space="preserve">
    <value>Czy jesteś pewien? To spowoduje blokadę wymian na minimum 7 dni.</value>
  </data>
  <data name="Authenticator_Unlink_Prompt_Title" xml:space="preserve">
    <value>Odłączyć?</value>
  </data>
  <data name="AccountsHeadline.Text" xml:space="preserve">
    <value>Konta</value>
  </data>
  <data name="LoginHeadline.Text" xml:space="preserve">
    <value>Zaloguj</value>
  </data>
  <data name="LoginBtn.Content" xml:space="preserve">
    <value>Zaloguj</value>
  </data>
  <data name="TxtAddAuthenticator.Text" xml:space="preserve">
    <value>Dodaj mobilny token urzytelniający</value>
  </data>
  <data name="TxtPhoneNumber.Text" xml:space="preserve">
    <value>Wpisz numer telefonu w następujący sposób: +{cC} Numer-telefonu (tj. +48 123-456-789).</value>
  </data>
  <data name="TxtUsername.Text" xml:space="preserve">
    <value>Nazwa użytkownika</value>
  </data>
  <data name="TxtPassword.Text" xml:space="preserve">
    <value>Hasło</value>
  </data>
  <data name="User_Logout_Prompt_Message" xml:space="preserve">
    <value>Czy jesteś pewien? To spowoduje usunięcie tego konta także z listy użytkowników.</value>
  </data>
  <data name="User_Logout_Prompt_Title" xml:space="preserve">
    <value>Wylogować?</value>
  </data>
  <data name="UiCommand_Yes_Text" xml:space="preserve">
    <value>Tak</value>
  </data>
  <data name="UiCommand_No_Text" xml:space="preserve">
    <value>Nie</value>
  </data>
  <data name="TxtEnterEmailCode.Text" xml:space="preserve">
    <value>Wpisz kod z e-maila</value>
  </data>
  <data name="TxtEnterTheCaptcha.Text" xml:space="preserve">
    <value>Wpisz znaki poniżej</value>
  </data>
  <data name="TxtEnterTwoFactor.Text" xml:space="preserve">
    <value>Wpisz kod z mobilnego tokena urzytelniającego</value>
  </data>
  <data name="LoginResult_GeneralFailure_Text" xml:space="preserve">
    <value>Nieznany błąd.</value>
  </data>
  <data name="LoginResult_BadRSA_Text" xml:space="preserve">
    <value>Nieznany błąd.</value>
  </data>
  <data name="LoginResult_BadCredentials_Text" xml:space="preserve">
    <value>Nieprawidłowe dane logowania.</value>
  </data>
  <data name="LoginResult_TooManyFailedLogins_Text" xml:space="preserve">
    <value>Za dużo błędów.</value>
  </data>
  <data name="Need2Fa" xml:space="preserve">
    <value>Potrzebny mobilny token urzytelniający.</value>
  </data>
  <data name="AreYouHuman" xml:space="preserve">
    <value>Czy jesteś człowiekiem?</value>
  </data>
  <data name="TxtLinkAuthenticatorHeadline.Text" xml:space="preserve">
    <value>Połącz mobilny token urzytelniający</value>
  </data>
  <data name="BtnLink.Content" xml:space="preserve">
    <value>Połącz</value>
  </data>
  <data name="TxtLinkAuthenticatorSummary.Text" xml:space="preserve">
    <value>Musisz ustawić to urządzenie jako mobilny token zanim będziesz uzyskiwać kody lub potwierdzenia wymian na Steam.</value>
  </data>
  <data name="SteamGuardButton.Label" xml:space="preserve">
    <value>Kody</value>
  </data>
  <data name="ConfirmationsButton.Label" xml:space="preserve">
    <value>Potwierdzenia</value>
  </data>
  <data name="MessageButton.Label" xml:space="preserve">
    <value>Chat</value>
  </data>
  <data name="UsersButton.Label" xml:space="preserve">
    <value>Zmień konto</value>
  </data>
  <data name="LogoutButton.Label" xml:space="preserve">
    <value>Wyloguj</value>
  </data>
  <data name="AboutButton.Label" xml:space="preserve">
    <value>O aplikacji</value>
  </data>
  <data name="BtnUnlink.Content" xml:space="preserve">
    <value>Odłącz</value>
  </data>
  <data name="BtnContinue.Content" xml:space="preserve">
    <value>Kontynuuj</value>
  </data>
  <data name="TxtSmsCode.Text" xml:space="preserve">
    <value>Wpisz kod z SMS-a</value>
  </data>
  <data name="Authenticator_Link_UnknownError_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Link_UnknownError_Message" xml:space="preserve">
    <value>Wystąpił nieznany błąd podczas łączenia mobilnego tokena.</value>
  </data>
  <data name="Authenticator_Link_AlreadyLinked_Title" xml:space="preserve">
    <value>Błąd</value>
  </data>
  <data name="Authenticator_Link_AlreadyLinked_Message" xml:space="preserve">
    <value>Już masz inne urządzenie ustawione jako mobilny token. Odłącz go od konta i spróbuj ponownie.</value>
  </data>
  <data name="EnterPhoneNumber" xml:space="preserve">
    <value>Wpisz numer telefonu</value>
  </data>
  <data name="BadCode" xml:space="preserve">
    <value>Zły kod</value>
  </data>
  <data name="TxtRevocationExp1.Text" xml:space="preserve">
    <value>Mobilny token nie został jeszcze połączony.

Przed zakończeniem, zapisz kod ratunkowy - pozwoli to odzyskać konto.</value>
  </data>
  <data name="TxtRevocationExp2.Text" xml:space="preserve">
    <value>Będziesz potrzebował tego kodu, jeśli stracisz swój telefon. NIE BĘDZIESZ MIAŁ MOŻLIWOŚCI ZOBACZYĆ GO PONOWNIE! Zapisz go więc, teraz.

Nikomu go nie podawaj.</value>
  </data>
  <data name="GeneratingCode_Ellipsis" xml:space="preserve">
    <value>Generowanie kodu...</value>
  </data>
  <data name="MainPage_AccountText_Format" xml:space="preserve">
    <value>{0} ({1})</value>
  </data>
  <data name="About_Headline.Text" xml:space="preserve">
    <value>Informacje o aplikacji</value>
  </data>
  <data name="About_AppVersion.Text" xml:space="preserve">
    <value>Wersja</value>
  </data>
  <data name="About_AppCreator.Text" xml:space="preserve">
    <value>Twórca</value>
  </data>
  <data name="About_AppSource.Text" xml:space="preserve">
    <value>Kod źródłowy</value>
  </data>
  <data name="NewUserButton.Label" xml:space="preserve">
    <value>Dodaj</value>
  </data>
  <data name="SwitchUserButton.Label" xml:space="preserve">
    <value>Zmień konto</value>
  </data>
</root>

**Comment by Top-Cat** [comment]
Please add me on steam if you haven't already, I have the translations in a format more usable by translators.
