### ISSUE TITLE
Hide revocation code

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#2]
The revocation code should be hidden (and also **not** be visible from the main view) once the user has noted it.

View the official notes from steam here: https://support.steampowered.com/kb_article.php?ref=4440-RTUI-9218

"_You will not be able to view it again after this step [...]_"

**Comment by Top-Cat** [comment]
That's not a should, just their implementation. Do you think this data is actually sensitive? I thought it more useful to provide it.

**Comment by Top-Cat** [comment]
Closing due to lack of response

**Comment by setoy** [comment]
That's certainly a way to handle this.

**Comment by Top-Cat** [comment]
Made you respond, so I guess it worked. Care to answer the question?

**Comment by setoy** [comment]
I believe the data you use to remove the authenticator thought to SECURE your account is sensitive, yes.
