### ISSUE TITLE
Show currently logged in user

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#3]
A good place would be the MainView. There you could show the currently logged-in user instead of the revocation could (which should actually not be permanently visible!).

**Comment by Top-Cat** [comment]
Or as a heading to the bottom menu?

**Comment by Top-Cat** [comment]
Closing due to lack of response

**Comment by setoy** [comment]
Honestly I don't care **where** it's shown... All I care about is that **is** shown.

Maybe you want to add it where the official authenticator [shows it](http://steamcdn-a.akamaihd.net/steam/mobile/setupfaq/IMG_6577.jpg)?
