### ISSUE TITLE
App crashing in confirmations

### ISSUE THREAD

**Issue by GAMELASTER** [Top-Cat/UnofficialSteamAuthenticator#4]
In Windows 10 latest fast build sometime app crash when run confirmations or select a offer. Maybe it is only W10 problem, but I will try to debug it and fix it. (maybe edge is...)

**Comment by Top-Cat** [comment]
Error message? Screenshot?

**Comment by GAMELASTER** [comment]
@Top-Cat
Sorry, i still not catched that, i dont have a debug version.
If i will deploy a debug version when i have a version downloaded from Store, the data from AppStorage be cleaned or not? (i dont want to loss a login informations and again wait 7 days of activation)

**Comment by Top-Cat** [comment]
Debug version?

I'm not asking for anything you can't do with the existing version of the app.
