### ISSUE TITLE
Add me as contributor

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#43]
Hello,

I would like to ask if you can add new branch to the project, editable for me.
The change I thought about is better documentation to this project, i. e. adding
to your code things like:
```
///<summary>
///Add session data to Application's storage.
///</summary>
```

**Comment by setoy** [comment]
Fork the repo and create a PR?

**Comment by Top-Cat** [comment]
tbf the only benefit of being a contributor is being able to mess around with issue labels/assignments

You can make a branch just as easily with or without it

**Comment by hypixus** [comment]
@Top-Cat OK then, I'll do the fork way.
