### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by DeFiXiK** [Top-Cat/UnofficialSteamAuthenticator#53]
Авторизация работает - это круто.
Но у меня возникли проблемы с привязкой аутентификатора.
Во первых, никак не исчезает окно "пароля восстановления"
Во вторых, даже если удалось избежать появления этого окна, путем закрытия и открытия приложения, и ввода своего номера +7********** я получил сообщение о неизвестной ошибке!
P.S. При этом смс на телефон приходит.
_______________________________________________________________________________
Authentification works - that's neat.
But I've got some problems when I was linking the authentificator.
First, password recovery window never dissappears.
Second, even if I avoid that window by reopening the app, I get an "unknown error" message when typing my phone number (+7xxxxxxxxxx).
P.S. By the way, I do receive the text message on my phone.

**Comment by Top-Cat** [comment]
What version of the app?
What happens when you try to load chat?
Have you tried adding your phone at https://store.steampowered.com/phone/manage first?
"password recovery window" ?
Which exact stage of linking fails?

**Comment by DeFiXiK** [comment]
* Version 1.4.98
* Chat works, I can even send a message
* Right after entering phone number
* Yes, I've added my phone there
* Sorry, not "password recovery", but "recovery password". I meant the window containing backup code, which is used to unlink a lost phone.

**Comment by mrlackride** [comment]
+
I have the same problem

**Comment by Top-Cat** [comment]
If you get an error after entering your phone number you can't get to the revocation code screen. Have you got some screenshots to illustrate what you mean by that?

Furthermore you shouldn't be asked for a phone number if one is already on your account, so there's something else going on and I need more information/steps to reproduce this issue. What setting do I need to change on my steam account to get this to happen?

**Comment by DeFiXiK** [comment]
You've got a video in another issue, which accurately depicts my problem.
