### ISSUE TITLE
Problem?

### ISSUE THREAD

**Issue by MaviS11** [Top-Cat/UnofficialSteamAuthenticator#56]
Hello,
I have a problem with that app. I've already added account and phone number. Next shows this code for losing phone case. Later comes SMS with verify code "Your Steam confirmation code is XXXXX".
And.. that's all. Nothing new shows, still is that code for losing phone possibility. What should I do with this code? Someone help me please?

**Comment by Top-Cat** [comment]
Could you provide a screenshot?

**Comment by MaviS11** [comment]
Ye
![123](https://cloud.githubusercontent.com/assets/18266800/14290168/439a41e0-fb5e-11e5-9ee9-9fb87aa316d9.png)
Its this menu as I said. SMS with this veryfication coming and that's all. Nothing happens. And now I've got problem because it wanted from my to write phone number and everytime is " there appeared unknown error while connecting mobile token with account". I've added my number on steam but it's still same....

**Comment by mrlackride** [comment]
i sent on you email video with problem

**Comment by mrlackride** [comment]
https://www.youtube.com/watch?v=zEbpOLnxAgU&feature=youtu.be

**Comment by mrlackride** [comment]
video with problem
sorry for quality

**Comment by MaviS11** [comment]
Yea, this video shows everything. Thanks for the imaging and I'm waiting for help, please

**Comment by Top-Cat** [comment]
What phone is that?

**Comment by MaviS11** [comment]
I mean that how i'm trying when im writting my number, it's shows (for me) unknown error...
I have Windows Phone, Microsoft Lumia 532, version 8.1.
I wanted to add that when i first install this app, it works correctly. But now something was happend and  yea, i can't connect phone with steam account.

**Comment by Top-Cat** [comment]
"this video shows everything"
So it doesn't?

**Comment by MaviS11** [comment]
Problem is that when code came, nothing happens.

**Comment by Top-Cat** [comment]
That is not unknown error

**Comment by mrlackride** [comment]
Nokia Lumia 820
Windows 10 mobile

**Comment by hypixus** [comment]
@mrlackride My list of (propably working) troubleshooting:
1. Try pressing back, after saving the code.
     If it's not visible, swipe up from bottom screen edge and then press it.
2. Check if you have any app opened in background, check it by holding back button
3. Try changing language in Settings of app to English. This may be caused by too long
    Russian translation, so button ending procedure of adding account may hide under
    the label.
4. In my case, some apps freezing, "wakes up" after going to opened app list(hold back
    button) and immediatedly coming back to app. This works on some games and apps.

Hope I helped, let me know if I've solved your problem,
Good luck

**Comment by Viiprogrammer** [comment]
I have the same problem

Windows 8.1
Lumia 530

**Comment by Top-Cat** [comment]
I've already fixed the code screen problem locally, working on testing though
Changing the app language to english is probably the best short term workaround

**Comment by mrlackride** [comment]
i dont have english language
i have only russian

**Comment by mrlackride** [comment]
thanks 
i set mobile authenithicator))))))))

**Comment by MaviS11** [comment]
As i said, now i have problem with connection my number with this app. I have already connected my phone with steam on computer but it still want's from me my number. It's show me like this:
Add your number phone in this way: +{cC} numberPhone (tj. +48-123-456-789). And how I should write this ? When im wrtiting like this: +{cC} (+48 XXX-XXX-XXX) it shows me error....

**Comment by mrlackride** [comment]
Mavis i have this problem
relogin and app start working

**Comment by MaviS11** [comment]
Yea i do this and now i have this problem "Problem is that when code came, nothing happens next."
Code is coming, and nothing happens, what should i do next?

**Comment by Top-Cat** [comment]
This issue is a mess of different people claiming random problems.

The original issue of not being able to scroll down to the continue button is FIXED, if you have a different issue you'll need to make your own issue.
