### ISSUE TITLE
Accounts occasionally got logged out on their own

### ISSUE THREAD

**Issue by fourzerofour** [Top-Cat/UnofficialSteamAuthenticator#57]
So lately upon starting the authenticator I am greeted with login screen so I have to input my login info again to sign in. I'm not getting prompted to go through the initial setup process though . Any idea why the accounts logged out on their own?

**Comment by Top-Cat** [comment]
When this happens is this button visible?

![Login Screen](http://i.imgur.com/qIGzvKl.png)

**Comment by fourzerofour** [comment]
Nope. http://i.imgur.com/wjkCD7S.png

**Comment by Top-Cat** [comment]
Still not much to go on, if this is only occasional is there a trigger because at the moment I can't reproduce this.
