### ISSUE TITLE
Import accounts

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#63]
Hello

is there any possibility to import accounts from SDA? I mean, we can export to .maFile-s (horray!) but we can't do this second way. Please, add this ability, or explain to people how to do this.

Thanks

hypixus

**Comment by Top-Cat** [comment]
Duplicate of #18

**Comment by hypixus** [comment]
@Top-Cat I meant import FROM sda, not to export :/

**Comment by Top-Cat** [comment]
#18 very clearly says "Export / Import to SDA"
What's your problem?

**Comment by hypixus** [comment]
I can't find it 😅

**Comment by Top-Cat** [comment]
Can't find what? Just read my comment.

**Comment by hypixus** [comment]
I did, few times, but please, provide me a step by step instruction :/

**Comment by Top-Cat** [comment]
I don't know what you need help with
