### ISSUE TITLE
Wrong description (readme.md)?

### ISSUE THREAD

**Issue by puzino-y-a** [Top-Cat/UnofficialSteamAuthenticator#65]
Hello,
in your description you have a link to http://windowsphone.com/s?appid=edcda38f-1eec-4f21-a267-190b4222f456 and there is an app with 85 reviews.
But, after I've searched Windows Store for an "Unofficial Steam Authenticator" it gives me only this one: https://www.microsoft.com/en-us/store/apps/unofficial-steam-authenticator/9nblggh58psp with 113 reviews. Previous one isn't listed at all.
Also, here, at the Steam thread (http://steamcommunity.com/discussions/forum/8/371918937255392935/) their 1st link is also to ***/9nblggh58psp .

Did you change your app ID or what? Will you add another link to prevent misunderstanding?
What version should I try?

Thanks!

**Comment by setoy** [comment]
Your first link redirects to all of the other links you've posted.

Depending on the link it may show reviews in your primary language or english. I only have 43 reviews on the app, because they're german. Overall, there are 113.

All of those links are the correct app.

**Comment by Top-Cat** [comment]
Yeah, the readme has the best link as it redirects to the version for your locale.
