### ISSUE TITLE
App is not showing trades

### ISSUE THREAD

**Issue by malkazar** [Top-Cat/UnofficialSteamAuthenticator#66]
App won't show trades and chat just showing the temporary code and when trying to show chat it says that there is a problem with connection with steam servers

**Comment by Top-Cat** [comment]
If it says there's a problem connecting with the steam servers then maybe there's a problem connecting with the steam servers... how long have you had this problem?

Can you provide exact error messages and screenshots?

**Comment by malkazar** [comment]
Yeah first time i had the same idea that is a temporary problem but it's 4 days since the app won't connect to the steam server i will give you 2 screenshot's the first blank one shows the effect of pushing the trades botton then it shows this blank page and returns to the mobile token code and the second one shows the chat it stays like there for 1-2 seconds and then returns to the mobile token code, i really care about this app because i really like WP and i'm angry about Microsoft and others that left WP users behind alone i hope that you will find a solution and btw if it can help you i'm using Nokia Lumia 735 with windows 10 preview with the best option of updates not the fast and even the slow mode and the problem started after an update of system.

**Comment by Top-Cat** [comment]
App version?

**Comment by malkazar** [comment]
V1.5.103

**Comment by malkazar** [comment]
If you're interested i found a user of your app that wrote the same problem as mine on reddit i will give you screenshot
![bez tytulu](https://cloud.githubusercontent.com/assets/18524909/14691170/0a2c1a2a-0750-11e6-97b2-e9df693a5a6e.png)

**Comment by Top-Cat** [comment]
Not the same version, not relevant

**Comment by malkazar** [comment]
No, i didn't because i tried to evade the 7 days punishment

**Comment by Top-Cat** [comment]
![Logout](https://cloud.githubusercontent.com/assets/534069/14761393/b9e5086a-0957-11e6-97a8-eb1afdedc2fc.png)

Further you never answered my first question.
> Can you provide exact error messages and screenshots?

None of your screenshots say anything about the connection to steam servers.

**Comment by setoy** [comment]
Relogging seems to have worked, then?
