### ISSUE TITLE
Library project

### ISSUE THREAD

**Issue by hypixus** [Top-Cat/UnofficialSteamAuthenticator#67]
Hello

I'm using your app since it appeared on Polish Windows Phone Store, and it works pretty well, with bugs handling.

You made awesome modifications to the SteamAuth Library, which allows it to run with other applications, too. I'm working on my own project - which works almost the same, but with few - key features for me, like working on maFiles instead of App Settings, and generating steam codes for selected time period.

My problem is, why did you make those(sorry, im just not the best at c# for windows phone) Callbacks? I mean, on original SteamAuth everything works by:
X.RefreshSession()
Y = X.FetchConfirmations()
for each (Confirmation item in Y)
{
X.DenyConfirmation()
}
And when I try to use those callbacks, button function does not even try to show message boxes correctly.

Please help,

Hypixus

**Comment by Top-Cat** [comment]
This is not the place to ask me questions

**Comment by hypixus** [comment]
Solved already, The question for future - where to ask questions like that?

**Comment by Top-Cat** [comment]
Directly, on steam?
