### ISSUE TITLE
Add prompt to logout

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#7]
Logging out should be prompted ("Do you really want to log out") because this is a *destroying* action since it deletes the account from the added list.

Or an undo operation, but I'd prefer the prompt...

[More on that](http://ux.stackexchange.com/questions/71960/deletion-confirm-or-undo-which-is-the-better-option-and-why)

**Comment by Top-Cat** [comment]
Yeah, I agree.
