### ISSUE TITLE
Do not login after reinstalling

### ISSUE THREAD

**Issue by Viiprogrammer** [Top-Cat/UnofficialSteamAuthenticator#76]
Hi, I have stopped working page trades and chat, I reinstalled the app, but when I went I require a code from Steam Guard Mobile Authenticator but it is nowhere, but I wrote the code of backup codes and I went but I did not opened a homepage Autnentikator, and asks to bind Autnentikator but he is already bound

**Comment by Top-Cat** [comment]
https://help.steampowered.com/en/wizard/HelpWithLoginInfo?nav=authenticator
