### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by fantis6** [Top-Cat/UnofficialSteamAuthenticator#79]
Hi, please build in a data export feature, this can be useful to,  for example i want shortly change my phone, and want export a data for new one.

**Comment by hypixus** [comment]
There is already. On user selection screen hold user you want to save and press "Export to SDA" or sth like that. Save it to your SD Card and move it to other phone. Install the app and use importing.

**Comment by hypixus** [comment]
To close.
