### ISSUE TITLE
Inconsistency between the account name and display name

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#8]
The user list displays the current authenticator code as well as the display name of the account. Very neat.

However, the main page displays **only** the account name.

Two ways to fix this:

- Add the account name to the user list, too (maybe below the authenticator code?)
- Also show the display name on the main page (maybe below the progress bar?)

**Comment by Top-Cat** [comment]
account name is far easier as it's returned from login, the user switch screen makes an additional api call.

No reason that can't be done though.

**Comment by setoy** [comment]
I'd prefer a fast and snappy response when opening the authenticator view (for it to let me enter my authenticator code fast).

I think the best way would be to cache the avatar and display name and refresh it asynchronously when visiting either the authenticator page or the user page.

**Comment by Top-Cat** [comment]
I didn't say anything about not caching, just why it's currently as it is as I wanted to get the user switch feature out first.

**Comment by setoy** [comment]
Didn't want to offend... Just used this to dump my thoughts :)

**Comment by Top-Cat** [comment]
This is basically implemented, old logins that aren't set up as 2FA didn't store the username.
Not much that can be done, if you log out and back in it'll pick it up.
