### ISSUE TITLE
Add i18n support

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#9]
I'll get to that once we've got my VS with the committed code running (check your reddit IM's for more details :))

**Comment by Top-Cat** [comment]
Yeah, that's why I've now committed the strings folder, should be able to source a few translations from friends too.

**Comment by setoy** [comment]
German seemingly completed with #16

**Comment by Top-Cat** [comment]
Users can now help here  https://crowdin.com/project/unofficial-steam-authenticator/invite

**Comment by adrie-dh** [comment]
It seems my dutch translation was accepted on Crowdin.
Let me know if you need more Dutch translation work done.

**Comment by Top-Cat** [comment]
Thanks @adrie-dh, I assume there'll be more to do as new features are added.

**Comment by Top-Cat** [comment]
Gonna close this as the feature is now fully added, just needs people to offer translations.
